package:
  name: elm
  version: {{ environ.get('GIT_DESCRIBE_TAG', 'notag') }}

source:
  path: ..

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0)|int }}

requirements:
  build:
    - python
    - setuptools

  run:
    - attrs
    - deap
    - dill
    - distributed
    - earthio
    - networkx
    - numba
    - numpy
    - pandas
    - python
    - requests
    - scikit-image
    - scikit-learn
    - scipy
    - xarray
    - yaml
    - six

about:
  home: http://github.com/ContinuumIO/elm
  license: MIT

extra:
  maintainers:
    - Peter Steinberg - Continuum Analytics - psteinberg [at] continuum [dot] io
    - Greg Brener     - Continuum Analytics - gbrener [at] continuum [dot] io

test:
  imports:
    - elm.config
    - elm.model_selection
    - elm.pipeline.pipeline
    - elm.pipeline.steps
    - elm.sample_util
    - elm.scripts

  requires:
    - pytest

  commands:
    - py.test -m 'not slow' -v $SP_DIR/elm  [unix]
    - py.test -m 'not slow' -v %SP_DIR%/elm  [win]
